### ISSUE TITLE
DES encrypt

### ISSUE THREAD

**Issue by RicardoFragoso99** [winkelsdorf/DelphiEncryptionCompendium#3]
Hi,

I need to encrypt some strings that are to be verified after with another application.
The other application is in C# and the send me this piece of source code:

 public static string encrypt(string value, string key)
        {
            DESCryptoServiceProvider des = new DESCryptoServiceProvider();
            des.Mode = CipherMode.CBC;
            des.Padding = PaddingMode.PKCS7;
            des.Key = ASCIIEncoding.ASCII.GetBytes(key);
            des.IV = ASCIIEncoding.ASCII.GetBytes(key);

             ICryptoTransform encryptor = des.CreateEncryptor();

             byte[] messageBytes = System.Text.ASCIIEncoding.ASCII.GetBytes(value);

            byte[] encryptedBytes = encryptor.TransformFinalBlock(messageBytes, 0, messageBytes.Length);

            return Convert.ToBase64String(encryptedBytes);
        }

I'm having trouble to make the encryptation compatible.

Example:
using: encrypt(“1234568”, "c9FC57w3");

I should have: bVRN+cnpPLvpJkRE+W5+JQ==

Can you help?

Thank you

**Comment by MHumm** [comment]
Which code did you write in your Delphi application for this? What's the output of your code? PaddingMode PKCS7 doesn't tell me much, sorry. The base 64 encoding fan be done by passing the appropriate formatting class to the encryption method.

**Comment by MHumm** [comment]
Issue closed as the requester did not show any Delphi code he tried to write for encrypting his strings within more than 3 years.
