### ISSUE TITLE
A ManualRegisterClasses define would be nice

### ISSUE THREAD

**Issue by mknox74** [winkelsdorf/DelphiEncryptionCompendium#7]
A define akin to DEC 3.0's ManualRegisterClasses would be nice to have. All the XXX.RegisterClass() calls in "initialization" section of a few modules could be surrounded by {$IFNDEF ManualRegisterClasses}.

The define could be placed in DECOptions.inc as disabled by default.

**Comment by MHumm** [comment]
I have good news for you: the next checkin to development branch will contain this define. I'm just wrapping up a bit of documentation before checking in.

**Comment by MHumm** [comment]
Checked into development branch now.
